name: .NET 

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest  

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 
      with:
        dotnet-version: 5.0.x
    - name: Restore Dependecies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
